import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight, ArrowDown, Clock3, Sparkles, Sprout, ScanHeart, BookOpen, Check, Flower2, Coffee, Fingerprint } from 'lucide-react';
import { ProfileCard, MiniLabel } from '@/components/ui';
import { getProfile } from '@/lib/coffee';
export default function Home() { return <main id="main">
<section className="hero wrap"><div className="hero-copy"><MiniLabel>A LITTLE SIP OF SELF-DISCOVERY</MiniLabel><h1>你是哪一種<br/><span className="hero-accent">咖啡小靈魂<svg className="title-spark" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" aria-hidden="true" focusable="false"><path d="M12 2v20M2 12h20M5 5l14 14M5 19 19 5"/></svg></span>？</h1><p className="hero-description">藏在日常裡的喜歡，<br/>也藏著屬於你的那杯咖啡。</p><p className="hero-sub">從一份甜點、一個理想的午後，<br/>發現你的風味偏好，遇見本命咖啡。</p><Link className="button primary hero-button" href="/quiz">找到我的本命咖啡 <ArrowRight size={18}/></Link><div className="hero-meta"><span><Clock3 size={14}/> 約 3 分鐘</span><i/><span>16 道小選擇</span><i/><span>不用懂咖啡</span></div></div><div className="hero-visual"><span className="handwritten hero-note">a little curious, a little caffeinated.</span><Image src="/images/hero.webp" alt="五隻可愛咖啡豆小精靈，圍著一杯咖啡，在花園裡享受午後" width={1536} height={1024} priority sizes="(max-width: 760px) 100vw, 60vw"/><div className="round-stamp"><span>FIND YOUR</span><Coffee size={25} strokeWidth={1.3}/><span>COFFEE SOUL</span></div><span className="visual-caption"><span>✦</span> 好喝的故事，從認識自己開始。</span></div></section>
<div className="flavor-ribbon" aria-hidden="true"><span>一點花香 <Flower2 size={17}/></span><span>一點果甜 <Sprout size={17}/></span><span>一點好奇 <Sparkles size={17}/></span><span>很多很多的你 <HeartIcon/></span><span>YOUR VIBE, YOUR BREW <Coffee size={17}/></span></div>
<section className="intro-section wrap" id="about"><div className="section-heading"><span className="eyebrow">NOT JUST A PERSONALITY TEST</span><h2>不只認識自己，<br className="mobile-break"/>也認識你會喜歡的味道。</h2><p>不需要咖啡知識，只需要一點點直覺。</p></div><div className="steps"><article><span className="step-number">01</span><div className="step-icon tone-pink"><ScanHeart size={28} strokeWidth={1.4}/></div><h3>跟著感覺，做小選擇</h3><p>喜歡的水果、嚮往的生活、想待的角落。<br/>每個答案，都是你的一小片。</p></article><article><span className="step-number">02</span><div className="step-icon tone-yellow"><Fingerprint size={28} strokeWidth={1.4}/></div><h3>遇見你的咖啡人格</h3><p>四條風味軸，組合成 16 種小靈魂。<br/>看看你的日常，藏著什麼風味。</p></article><article><span className="step-number">03</span><div className="step-icon tone-sage"><BookOpen size={28} strokeWidth={1.4}/></div><h3>帶著護照，喝一杯吧</h3><p>從焙度到產區，幫你整理好了。<br/>把點單小抄拿給咖啡師，就能出發。</p></article></div></section>
<section className="characters-section"><div className="wrap"><div className="section-heading horizontal"><div><span className="eyebrow">MEET THE LITTLE BEANS</span><h2>16 種小靈魂，<br className="mobile-break"/>每一種都很有味道。</h2><p>你會是花香漫遊者，還是午夜可可家？</p></div><Link className="text-link" href="/types">看看全部 16 型 <ArrowRight size={17}/></Link></div><div className="featured-grid">{['BCLA','BFLA','DCRS','DFRS'].map(code=><ProfileCard key={code} profile={getProfile(code)!}/>)}</div></div></section>
<section className="closing-section wrap"><div className="closing-flower"><Flower2 size={54} strokeWidth={1}/></div><span className="eyebrow">A GOOD CUP STARTS WITH YOU</span><h2>你的下一杯，<br/>也許會有一點不一樣。</h2><p>沒有最好的咖啡，只有你剛好喜歡的味道。</p><Link href="/quiz" className="button primary">出發，找我的咖啡 <ArrowRight size={17}/></Link><div className="small-assurances"><span><Check size={13}/> 不用註冊</span><span><Check size={13}/> 免費探索</span><span><Check size={13}/> 結果可以帶走</span></div></section>
<section className="method-note wrap"><Sprout size={21}/><p>BeanTI 是風味探索小遊戲，不是心理診斷。感官偏好是推薦的主要依據，情境與人格題增添一點趣味。每一批豆子都有不同個性，實際喝過的喜歡，永遠比測驗更重要。</p><Link href="/types#axes" aria-label="了解四條咖啡風味軸"><ArrowDown size={18}/></Link></section>
</main>;}
function HeartIcon(){return <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/></svg>}
