'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { ArrowRight, Bean, Coffee, Droplets, Flower2, Cherry, Citrus, Cookie, Waves, MapPin } from 'lucide-react';
import { origins, processes, flavors, explorationDefaults } from '@/lib/explore';
import { getProfile } from '@/lib/coffee';
const flavorIcons = [Flower2,Citrus,Cherry,Cookie,Bean,Waves];
function ProcessDrawing({method}:{method:string}) {
 const natural=method==='natural',honey=method==='honey',anaerobic=method==='anaerobic';
 return <svg className="process-drawing" viewBox="0 0 340 240" aria-hidden="true" stroke="var(--ink)" strokeWidth="1.6" fill="none">
 <circle cx="170" cy="118" r="101" stroke="var(--line)" strokeDasharray="3 7"/>
 {anaerobic?<><rect x="112" y="40" width="116" height="160" rx="22" fill="var(--sage)"/><path d="M123 40V29h94v11M126 70h88M124 179h92"/><path d="M158 28V17h33v12"/>{[0,1,2,3,4,5].map(i=><g key={i} transform={`translate(${141+i%3*29} ${113+Math.floor(i/3)*35})`}><ellipse rx="11" ry="15" fill="var(--pink)"/><path d="M0-9q-5 10 0 18"/></g>)}<path d="M154 86v10m20-13v8m19-5v12" stroke="var(--green)"/></>:<><ellipse className="fruit-layer" cx="170" cy="118" rx={natural?77:honey?57:43} ry={natural?91:honey?73:58} fill={natural?'var(--pink)':honey?'var(--yellow)':'var(--sage)'}/>{natural&&<path d="M169 28q0-22 20-24" stroke="var(--green)"/>}<ellipse cx="170" cy="118" rx="39" ry="55" fill="var(--sage)"/><path d="M173 72c-27 25 25 57-5 91" stroke="var(--green)" strokeWidth="3"/>{honey&&<path d="M121 99q-6 21 0 43M220 104q5 15 0 31" stroke="var(--ink)"/>}</>}
 <path d="M210 130h45l16-18h45"/><circle cx="210" cy="130" r="3" fill="var(--paper)"/>
 </svg>;
}
export default function FlavorExplorer(){
 const params=useSearchParams();const profile=getProfile(params.get('type')??'');const defaults=explorationDefaults(profile?.code);
 const origin=origins.find(o=>o.id===params.get('origin'))??origins.find(o=>o.id===defaults.origin)!;
 const process=processes.find(p=>p.id===params.get('method'))??processes.find(p=>p.id===defaults.method)!;
 const flavor=flavors.find(f=>f.id===params.get('flavor'))??flavors.find(f=>f.id===defaults.flavor)!;
 const FlavorIcon=flavorIcons[flavors.findIndex(f=>f.id===flavor.id)];
 function choose(key:string,value:string){const next=new URLSearchParams(params.toString());next.set(key,value);window.history.replaceState(null,'',`/explore?${next.toString()}${window.location.hash}`);}
 return <>
 {profile&&<div className="explore-personal"><Bean size={21} aria-hidden="true"/><p>從 <strong>{profile.name}</strong> 的風味方向出發。這是探索起點，每一種味道都可以試試。</p><Link href={`/result/${profile.code}`} className="text-link">回到人格卡 <ArrowRight size={15}/></Link></div>}
 <nav className="explore-index" aria-label="風味筆記章節"><a href="#origins">01 / 產區小旅行</a><a href="#processing">02 / 果實的變身</a><a href="#flavors">03 / 用自己的話品飲</a></nav>
 <section id="origins" className="explore-chapter" aria-labelledby="origins-heading"><div className="explore-heading"><span className="eyebrow">01 / A SENSE OF PLACE</span><h2 id="origins-heading">第一站，豆子的家鄉。</h2><p>先選一個產區，收下一張風味明信片。</p></div><div className="explore-options" role="group" aria-label="選擇產區">{origins.map(o=><button key={o.id} aria-pressed={origin.id===o.id} onClick={()=>choose('origin',o.id)}>{o.name}<span>{o.english}</span></button>)}</div>
 <article className="origin-postcard" aria-live="polite" aria-atomic="true"><div className="origin-picture"><span className="postcard-mark">A LITTLE POSTCARD FROM</span><span className="origin-english">{origin.english}</span><Image src={`/images/bean-${origin.art}.webp`} width={400} height={400} unoptimized alt={`${origin.name}風味旅行的咖啡豆小精靈`}/><span className="origin-stamp"><MapPin size={18} aria-hidden="true"/> BEANTI<br/>COFFEE JOURNAL</span><span className="origin-picture-note">a place to begin, a taste to discover.</span></div><div className="origin-copy"><span className="eyebrow"><MapPin size={14} aria-hidden="true"/>{origin.region}</span><h3>{origin.title}</h3><p>{origin.description}</p><div className="flavor-tags">{origin.tags.map(tag=><span key={tag}>{tag}</span>)}</div><div className="explore-tip"><strong>下一杯的小實驗</strong><p>{origin.try}</p></div><a className="text-link" href={`https://www.cafeimports.com/north-america/${origin.id}`}>閱讀產區資料 · Cafe Imports <ArrowRight size={14}/></a></div></article><p className="explore-footnote">這些是常見的風味線索，不是產地保證。品種、微氣候、處理法、焙度與沖煮，都會改變杯中的表現。</p></section>
 <section id="processing" className="explore-chapter" aria-labelledby="process-heading"><div className="explore-heading"><span className="eyebrow">02 / FROM CHERRY TO BEAN</span><h2 id="process-heading">同樣是果實，走不同的路。</h2><p>切換處理方式，看看乾燥前留下了什麼。</p></div><div className="explore-options" role="group" aria-label="選擇處理法">{processes.map(p=><button key={p.id} aria-pressed={process.id===p.id} onClick={()=>choose('method',p.id)}>{p.name}<span>{p.english}</span></button>)}</div><div className="process-notebook" aria-live="polite" aria-atomic="true"><div className="process-art"><ProcessDrawing method={process.id}/><span>{process.layer}</span><small>結構簡化示意</small></div><div className="process-copy"><span className="eyebrow">{process.english}</span><h3>{process.title}</h3><p>{process.description}</p><ol className="process-path">{process.steps.map((s,i)=><li key={s}><span>0{i+1}</span>{s}</li>)}</ol><p className="process-note">{process.note}</p></div></div><div className="comparison-note"><Droplets size={23} aria-hidden="true"/><p><strong>帶著這個問題，試喝{process.name}的批次</strong><br/>{process.question}</p></div><p className="explore-footnote">這一區介紹處理法本身，不推算上方產區與處理法組合的味道，也不表示每個產區都有所有處理批次。</p></section>
 <section id="flavors" className="explore-chapter" aria-labelledby="flavors-heading"><div className="explore-heading"><span className="eyebrow">03 / FIND YOUR OWN WORDS</span><h2 id="flavors-heading">你喝到的，比標準答案重要。</h2><p>點選一種風味，練習把「好喝」說得更具體。</p></div><div className="flavor-workbench"><div className="flavor-picks" role="group" aria-label="選擇風味">{flavors.map((f,i)=>{const Icon=flavorIcons[i];return <button key={f.id} aria-pressed={flavor.id===f.id} onClick={()=>choose('flavor',f.id)}><Icon size={25} strokeWidth={1.4} aria-hidden="true"/><span>{f.name}</span><ArrowRight size={14} aria-hidden="true"/></button>;})}</div><article className={`flavor-note tone-${flavor.color}`} aria-live="polite" aria-atomic="true"><div className="flavor-note-top"><FlavorIcon size={46} strokeWidth={1.1} aria-hidden="true"/><span className="eyebrow">{flavor.english}</span></div><h3>{flavor.name}</h3><span className="flavor-examples">{flavor.examples}</span><p>{flavor.description}</p><div className="explore-tip"><strong>下一口，這樣試試</strong><p>{flavor.tip}</p></div></article></div><p className="explore-footnote">風味詞是感官聯想，不是配料表。一般未加香的咖啡，標示「莓果」不表示加入莓果；特殊浸漬或增味批次，請另看店家的處理說明。</p></section>
 <section className="explore-outro"><Coffee size={30} strokeWidth={1.3} aria-hidden="true"/><h2>懂一點點，就多一點樂趣。</h2><p>帶著剛剛的好奇，親手走過一杯咖啡的誕生。</p><Link href="/brew" className="button primary">準備器具，沖一杯 <ArrowRight size={17}/></Link><Link href={profile?`/result/${profile.code}`:'/quiz'} className="text-link">{profile?'帶著人格卡去點一杯':'還不知道喜歡什麼？測測我的咖啡人格'} <ArrowRight size={15}/></Link></section>
 <details className="explore-sources"><summary>筆記的參考資料</summary><p>內容為 BeanTI 整理的入門說明，風味描述不代表實測數值或特定批次保證。</p><a href="https://www.cafeimports.com/north-america/processes">Cafe Imports · 咖啡處理法</a><a href="https://www.cafeimports.com/north-america/fermentation">Cafe Imports · 發酵與處理流程</a><a href="https://worldcoffeeresearch.org/read-more/news/174-world-coffee-research-sensory-lexicon">World Coffee Research · 感官詞彙</a></details>
 </>;
}
