import Link from 'next/link';
import Image from 'next/image';
import { ArrowUpRight, Bean, Coffee, Heart } from 'lucide-react';
import type { Profile } from '@/lib/coffee';
export function Header() { return <header className="header"><Link href="/" className="brand" aria-label="BeanTI 首頁"><Bean size={27} strokeWidth={1.7}/><span>bean<span className="brand-ti">ti</span><span className="brand-dot">.</span></span></Link><nav aria-label="主要導覽"><Link href="/types">16 型咖啡圖鑑</Link><Link href="/explore" className="nav-about">風味小旅行</Link><Link href="/brew" className="nav-about">一起沖一杯</Link><Link href="/quiz" className="nav-start">測測我的咖啡人格 <ArrowUpRight size={15}/></Link></nav></header>; }
export function Footer() { return <footer className="footer"><Link href="/" className="footer-brand"><Bean size={19}/> beanti.</Link><span>每個人，都有自己的一杯。</span><span className="footer-note">Made with <Heart size={12}/> & a little caffeine</span></footer>; }
export function BeanArt({profile,priority=false,className=''}:{profile:Profile;priority?:boolean;className?:string}) { return <Image unoptimized className={`bean-art ${className}`} src={`/images/bean-${profile.art}.webp`} width={400} height={400} alt={`${profile.name}咖啡豆小精靈插畫`} priority={priority}/>; }
export function ProfileCard({profile}:{profile:Profile}) { return <Link className={`profile-card tone-${profile.color}`} href={`/result/${profile.code}`}><div className="card-top"><span className="type-code">{profile.code}</span><ArrowUpRight size={17}/></div><BeanArt profile={profile}/><div className="profile-card-copy"><span className="english">{profile.english}</span><h3>{profile.name}</h3><p>{profile.flavors.join(' · ')}</p></div></Link>; }
export function MiniLabel({children}:{children:React.ReactNode}) {return <span className="eyebrow"><Coffee size={14}/>{children}</span>;}
